-- MIGRATION SCRIPT FROM 10 TO 11

-- TRANSACTION_STATUS TO CONTRACT_STATUS
ALTER TABLE INSURANCE_REQUEST
	CHANGE COLUMN TRANSACTION_STATUS CONTRACT_STATUS VARCHAR(255) AFTER AGREEMENT_NUMBER;

-- NOT_COMPLETED TO CANCELED
UPDATE INSURANCE_REQUEST
	SET CONTRACT_STATUS = 'CANCELED'
	WHERE CONTRACT_STATUS = 'NOT_COMPLETED';

-- TRANSACTION_PROBLEM TO REQUEST_CANCELATION_REASON
ALTER TABLE INSURANCE_REQUEST
	CHANGE COLUMN TRANSACTION_PROBLEM REQUEST_CANCELATION_REASON VARCHAR(255);

-- CLOSED, CLOSED_BY AND STATUS REPLACED BY ARCHIVED

DROP INDEX REQUEST_IDX01 ON REQUEST;
DROP INDEX REQUEST_IDX02 ON REQUEST;
DROP INDEX REQUEST_IDX03 ON REQUEST;
ALTER TABLE REQUEST
	DROP FOREIGN KEY FK_REQUEST_CLOSED_BY_USER_ID,
	DROP KEY FK_REQUEST_CLOSED_BY_USER_ID,
	DROP COLUMN CLOSED,
	DROP COLUMN CLOSED_BY_USER_ID;

ALTER TABLE REQUEST
	ADD COLUMN ARCHIVED TINYINT(1) default 0 AFTER DTYPE;

CREATE INDEX IX_REQUEST_CREATED ON REQUEST (CREATED);
CREATE INDEX IX_REQUEST_ARCHIVED ON REQUEST (ARCHIVED);

UPDATE REQUEST
	SET ARCHIVED = '1'
	WHERE STATUS = 'CLOSED';
	
UPDATE REQUEST
	SET ARCHIVED = '0'
	WHERE STATUS = 'OPEN';

ALTER TABLE REQUEST
	DROP COLUMN STATUS;

-- REQUEST_CANCELATION_REASON TO INSURANCE_REQUEST_CANCELLATION_REASON
-- CONTRACT_STATUS TO INSURANCE_REQUEST_STATUS

ALTER TABLE INSURANCE_REQUEST
	CHANGE COLUMN REQUEST_CANCELATION_REASON INSURANCE_REQUEST_CANCELLATION_REASON VARCHAR(255) AFTER AGREEMENT_NUMBER,
	CHANGE COLUMN CONTRACT_STATUS INSURANCE_REQUEST_STATUS VARCHAR(255) AFTER INSURANCE_REQUEST_CANCELLATION_REASON;

-- RENAME INSURACNCE_REQUEST_STATUS VALUES

UPDATE INSURANCE_REQUEST
	SET INSURANCE_REQUEST_STATUS = 'POLICY_ISSUED'
	WHERE PAYMENT_STATUS = 'PENDING';

UPDATE INSURANCE_REQUEST
	SET INSURANCE_REQUEST_STATUS = 'PREMIUM_PAID'
	WHERE PAYMENT_STATUS = 'DONE';

UPDATE INSURANCE_REQUEST
	SET INSURANCE_REQUEST_STATUS = 'REQUEST_CANCELED'
	WHERE PAYMENT_STATUS = 'CANCELED';

UPDATE INSURANCE_REQUEST
	SET INSURANCE_REQUEST_STATUS = 'PENDING'
	WHERE INSURANCE_REQUEST_STATUS IS NULL;


-- ADD DATE_OF_PAYMENT

ALTER TABLE POLICY
	ADD COLUMN DATE_OF_PAYMENT DATE AFTER POLICY_NUMBER;

ALTER TABLE CASCO
	ADD COLUMN DATE_OF_PAYMENT DATE AFTER NO_POLICE_CALL_REQUIRED;

/*
 * VERSION TABLE
 */
DROP TABLE INSURANCE_VER_10;
CREATE TABLE INSURANCE_VER_11 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
