-- MIGRATION SCRIPT FROM 2.5 TO 2.5.1

/*
 * policy termination reason
 */

ALTER TABLE POLICY
	ADD COLUMN TERMINATION_REASON VARCHAR(255) AFTER POLICY_NUMBER;

/*
 * VERSION TABLE
 */
DROP TABLE INSURANCE_VER_2_5;
CREATE TABLE INSURANCE_VER_2_5_1 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
