-- MIGRATION SCRIPT FROM 2.4.4 TO 2.4.4.1


/*
 * VERSION TABLE
 */
DROP TABLE IF EXISTS INSURANCE_VER_2_4_1;
DROP TABLE IF EXISTS INSURANCE_VER_2_4_4;
CREATE TABLE INSURANCE_VER_2_4_4_1 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
