-- MIGRATION SCRIPT FROM 2.5.2 TO 2.5.3

/* 
 * no poses
 */
ALTER TABLE POS_CONTACT_EMAIL DROP FOREIGN KEY FK_POS_CONTACT_EMAIL_POS_ID;

ALTER TABLE POS_CONTACT_PHONE DROP FOREIGN KEY FK_POS_CONTACT_PHONE_POS_ID;

ALTER TABLE ADDRESS_STREET_LOCALIZATION 
	DROP FOREIGN KEY FK_ADDRESS_STREET_LOCALIZATION_ENTITY_ID,
	DROP KEY UNQ_ADDRESS_STREET_LOCALIZATION_0;

ALTER TABLE POS_NAME_LOCALIZATION
	DROP FOREIGN KEY FK_POS_NAME_LOCALIZATION_ENTITY_ID,
	DROP KEY UNQ_POS_NAME_LOCALIZATION_0;

DROP TABLE POS_CONTACT_EMAIL;
DROP TABLE POS_CONTACT_PHONE;
DROP TABLE POS;
DROP TABLE ADDRESS_STREET_LOCALIZATION;
DROP TABLE POS_NAME_LOCALIZATION;


/*
 * update Turkistan area
 */
UPDATE VEHICLE SET REGISTRATION_AREA = 'OTRK' WHERE REGISTRATION_AREA = 'OUK';


/*
 * VERSION TABLE
 */
DROP TABLE INSURANCE_VER_2_5_2;
CREATE TABLE INSURANCE_VER_2_5_3 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
