-- MIGRATION SCRIPT FROM 2.5 TO 2.6




-- --->> MIGRATION FROM 2.5 TO 2.5.1

/*
 * policy termination reason
 */

ALTER TABLE POLICY
	ADD COLUMN TERMINATION_REASON VARCHAR(255) AFTER POLICY_NUMBER;

-- <<--- MIGRATION FROM 2.5 TO 2.5.1

/* 
 * no poses
 */
ALTER TABLE POS_CONTACT_EMAIL DROP FOREIGN KEY FK_POS_CONTACT_EMAIL_POS_ID;

ALTER TABLE POS_CONTACT_PHONE DROP FOREIGN KEY FK_POS_CONTACT_PHONE_POS_ID;

ALTER TABLE ADDRESS_STREET_LOCALIZATION 
	DROP FOREIGN KEY FK_ADDRESS_STREET_LOCALIZATION_ENTITY_ID,
	DROP KEY UNQ_ADDRESS_STREET_LOCALIZATION_0;

ALTER TABLE POS_NAME_LOCALIZATION
	DROP FOREIGN KEY FK_POS_NAME_LOCALIZATION_ENTITY_ID,
	DROP KEY UNQ_POS_NAME_LOCALIZATION_0;

DROP TABLE POS_CONTACT_EMAIL;
DROP TABLE POS_CONTACT_PHONE;
DROP TABLE POS;
DROP TABLE ADDRESS_STREET_LOCALIZATION;
DROP TABLE POS_NAME_LOCALIZATION;


/*
 * update Turkistan area
 */
UPDATE VEHICLE SET REGISTRATION_AREA = 'OTRK' WHERE REGISTRATION_AREA = 'OUK';

-- --->> MIGRATION FROM 2.5.1 TO 2.5.2

/*
 * drop images
 */

ALTER TABLE IDENTITY_CARD 
	DROP FOREIGN KEY FK_IDENTITY_CARD_BACKSIDE_IMAGE_ID,
	DROP FOREIGN KEY FK_IDENTITY_CARD_FRONTSIDE_IMAGE_ID,
	DROP COLUMN BACKSIDE_IMAGE_ID,
	DROP COLUMN FRONTSIDE_IMAGE_ID; 

ALTER TABLE VEHICLE_CERTIFICATE 
	DROP FOREIGN KEY FK_VEHICLE_CERTIFICATE_BACKSIDE_IMAGE_ID,
	DROP FOREIGN KEY FK_VEHICLE_CERTIFICATE_FRONTSIDE_IMAGE_ID,
	DROP COLUMN BACKSIDE_IMAGE_ID,
	DROP COLUMN FRONTSIDE_IMAGE_ID; 

ALTER TABLE DRIVER_LICENSE
	DROP FOREIGN KEY FK_DRIVER_LICENSE_BACKSIDE_IMAGE_ID,
	DROP FOREIGN KEY FK_DRIVER_LICENSE_FRONTSIDE_IMAGE_ID,
	DROP COLUMN BACKSIDE_IMAGE_ID,
	DROP COLUMN FRONTSIDE_IMAGE_ID; 

ALTER TABLE CASCO_VEHICLE 
	DROP FOREIGN KEY FK_CASCO_VEHICLE_VIEW1_IMAGE_ID,
	DROP FOREIGN KEY FK_CASCO_VEHICLE_VIEW3_IMAGE_ID,
	DROP FOREIGN KEY FK_CASCO_VEHICLE_VIEW2_IMAGE_ID,
	DROP FOREIGN KEY FK_CASCO_VEHICLE_VIEW4_IMAGE_ID,
	DROP COLUMN VIEW1_IMAGE_ID,
	DROP COLUMN VIEW2_IMAGE_ID,
	DROP COLUMN VIEW3_IMAGE_ID,
	DROP COLUMN VIEW4_IMAGE_ID;

DROP TABLE IMAGE;

-- <<--- MIGRATION FROM 2.5.1 TO 2.5.2

-- --->> MIGRATION FROM 2.5.2 TO 2.5.3



-- <<--- MIGRATION FROM 2.5.2 TO 2.5.3



/*
 * VERSION TABLE
 */
DROP TABLE INSURANCE_VER_2_5;
CREATE TABLE INSURANCE_VER_2_6 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
