-- MIGRATION SCRIPT FROM 2.4.3 TO 2.4.4

/*
 * OPTLOCK
 */
ALTER TABLE IMAGE ADD COLUMN OPTLOCK DATETIME AFTER MIME_TYPE;
ALTER TABLE IDENTITY_CARD ADD COLUMN OPTLOCK DATETIME AFTER TYPE;
ALTER TABLE VEHICLE_CERTIFICATE ADD COLUMN OPTLOCK DATETIME AFTER VEHICLE_REGISTRATION_NUMBER;
ALTER TABLE USER ADD COLUMN OPTLOCK DATETIME AFTER NAME;
ALTER TABLE USER_LOGIN ADD COLUMN OPTLOCK DATETIME AFTER NAME;
ALTER TABLE POS_CONTACT_EMAIL ADD COLUMN OPTLOCK DATETIME AFTER EMAIL_ADDRESS;
ALTER TABLE POS_CONTACT_PHONE ADD COLUMN OPTLOCK DATETIME AFTER PHONE_TYPE;
ALTER TABLE USER_GROUP ADD COLUMN OPTLOCK DATETIME AFTER NAME;
ALTER TABLE REQUEST ADD COLUMN OPTLOCK DATETIME AFTER UPDATED;
ALTER TABLE DRIVER_LICENSE ADD COLUMN OPTLOCK DATETIME AFTER NUMBER;
ALTER TABLE INSURANCE_REQUEST ADD COLUMN OPTLOCK DATETIME AFTER yyy;
ALTER TABLE POS ADD COLUMN OPTLOCK DATETIME AFTER IS_PICKUP_AVAILABLE;
ALTER TABLE VEHICLE ADD COLUMN OPTLOCK DATETIME AFTER MODEL_NAME;
ALTER TABLE DRIVER ADD COLUMN OPTLOCK DATETIME AFTER ID_NUMBER;
ALTER TABLE POLICY ADD COLUMN OPTLOCK DATETIME AFTER ID;
ALTER TABLE CASCO ADD COLUMN OPTLOCK DATETIME AFTER THIRD_PARTY_LIABILITY_COVERAGE;

/*
 * VERSION TABLE
 */
DROP TABLE INSURANCE_VER_2_4_3;
CREATE TABLE INSURANCE_VER_2_4_4 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
