-- MIGRATION SCRIPT FROM 10 TO 11

-- TRANSACTION_STATUS TO CONTRACT_STATUS
ALTER TABLE INSURANCE_REQUEST
	CHANGE COLUMN TRANSACTION_STATUS CONTRACT_STATUS VARCHAR(255) AFTER AGREEMENT_NUMBER;

/*
 * VERSION TABLE
 */
DROP TABLE INSURANCE_VER_10;
CREATE TABLE INSURANCE_VER_11 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
