-- MIGRATION SCRIPT FROM 2.4.3 TO 2.4.4

/*
 * opt lock
 */
ALTER TABLE IMAGE ADD COLUMN UPDATED DATETIME NOT NULL AFTER MIME_TYPE;
UPDATE IMAGE SET UPDATED = NOW();

ALTER TABLE IDENTITY_CARD ADD COLUMN UPDATED DATETIME NOT NULL AFTER TYPE;
UPDATE IDENTITY_CARD SET UPDATED = NOW();

ALTER TABLE VEHICLE_CERTIFICATE ADD COLUMN UPDATED DATETIME NOT NULL AFTER VEHICLE_REGISTRATION_NUMBER;
UPDATE VEHICLE_CERTIFICATE SET UPDATED = NOW();

ALTER TABLE USER ADD COLUMN UPDATED DATETIME NOT NULL AFTER NAME;
UPDATE USER SET UPDATED = NOW();

ALTER TABLE USER_LOGIN ADD COLUMN UPDATED DATETIME NOT NULL AFTER NAME;
UPDATE USER_LOGIN SET UPDATED = NOW();

ALTER TABLE POS_CONTACT_EMAIL ADD COLUMN UPDATED DATETIME NOT NULL AFTER EMAIL_ADDRESS;
UPDATE POS_CONTACT_EMAIL SET UPDATED = NOW();

ALTER TABLE POS_CONTACT_PHONE ADD COLUMN UPDATED DATETIME NOT NULL AFTER PHONE_TYPE;
UPDATE POS_CONTACT_PHONE SET UPDATED = NOW();

ALTER TABLE USER_GROUP ADD COLUMN UPDATED DATETIME NOT NULL AFTER NAME;
UPDATE USER_GROUP SET UPDATED = NOW();

ALTER TABLE DRIVER_LICENSE ADD COLUMN UPDATED DATETIME NOT NULL AFTER NUMBER;
UPDATE DRIVER_LICENSE SET UPDATED = NOW();

ALTER TABLE POS ADD COLUMN UPDATED DATETIME NOT NULL AFTER IS_PICKUP_AVAILABLE;
UPDATE POS SET UPDATED = NOW();

ALTER TABLE VEHICLE ADD COLUMN UPDATED DATETIME NOT NULL AFTER MODEL_NAME;
UPDATE VEHICLE SET UPDATED = NOW();

ALTER TABLE DRIVER ADD COLUMN UPDATED DATETIME NOT NULL AFTER ID_NUMBER;
UPDATE DRIVER SET UPDATED = NOW();

ALTER TABLE POLICY ADD COLUMN UPDATED DATETIME NOT NULL AFTER ID;
UPDATE POLICY SET UPDATED = NOW();

ALTER TABLE CASCO ADD COLUMN UPDATED DATETIME NOT NULL AFTER THIRD_PARTY_LIABILITY_COVERAGE;
UPDATE CASCO SET UPDATED = NOW();

/*
 * VERSION TABLE
 */
DROP TABLE INSURANCE_VER_2_4_3;
CREATE TABLE INSURANCE_VER_2_4_4 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
