-- MIGRATION SCRIPT FROM 2.4 TO 2.5

ALTER TABLE POLICY DROP COLUMN PAID_AMOUNT_TO_BE_REMOVED_IN_THE_NEXT_RELEASE; 
ALTER TABLE CASCO DROP COLUMN PAID_AMOUNT_TO_BE_REMOVED_IN_THE_NEXT_RELEASE;

-- --->> MIGRATION FROM 2.4 TO 2.4.1

/*
 * CALLBACK-INSURANCE-REQUEST
 */

INSERT INTO INSURANCE_REQUEST 
	(
		ID,
		AGREEMENT_NUMBER,
		TRANSACTION_PROBLEM,
		TRANSACTION_STATUS,
		RTYPE, 
		PAYMENT_AMOUNT,
		PAYMENT_CURRENCY,
		PAYMENT_INSTANT,
		PAYMENT_INVOICE_NUMBER,
		PAYMENT_METHOD_NAME,
		PAYMENT_REFERENCE,
		PAYMENT_STATUS
	)
	SELECT
		ID,
		NULL,
		NULL,
		NULL,
		'UNCOMPLETE', 
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		'UNDEFINED'
	FROM CALLBACK_REQUEST; 

ALTER TABLE REQUEST DROP COLUMN SOURCE;

-- <<--- MIGRATION FROM 2.4 TO 2.4.1

-- --->> MIGRATION FROM 2.4.1 TO 2.4.2

ALTER TABLE INSURANCE_REQUEST
	ADD COLUMN  PAYMENT_CARD VARCHAR(255) AFTER PAYMENT_AMOUNT;

-- --->> MIGRATION FROM 2.4.1 TO 2.4.2

-- --->> MIGRATION FROM 2.4.2 TO 2.4.3

ALTER TABLE INSURANCE_REQUEST
	ADD COLUMN PAYER_NAME VARCHAR(255) AFTER PAYMENT_METHOD_NAME;

ALTER TABLE REQUEST
	MODIFY COLUMN NOTE LONGTEXT;

-- --->> MIGRATION FROM 2.4.2 TO 2.4.3

	
-- --->> MIGRATION FROM 2.4.3 TO 2.4.4

/*
 * opt lock
 */
ALTER TABLE IMAGE ADD COLUMN UPDATED DATETIME NOT NULL AFTER MIME_TYPE;
UPDATE IMAGE SET UPDATED = NOW();

ALTER TABLE IDENTITY_CARD ADD COLUMN UPDATED DATETIME NOT NULL AFTER TYPE;
UPDATE IDENTITY_CARD SET UPDATED = NOW();

ALTER TABLE VEHICLE_CERTIFICATE ADD COLUMN UPDATED DATETIME NOT NULL AFTER VEHICLE_REGISTRATION_NUMBER;
UPDATE VEHICLE_CERTIFICATE SET UPDATED = NOW();

ALTER TABLE USER ADD COLUMN UPDATED DATETIME NOT NULL AFTER NAME;
UPDATE USER SET UPDATED = NOW();

ALTER TABLE USER_LOGIN ADD COLUMN UPDATED DATETIME NOT NULL AFTER NAME;
UPDATE USER_LOGIN SET UPDATED = NOW();

ALTER TABLE POS_CONTACT_EMAIL ADD COLUMN UPDATED DATETIME NOT NULL AFTER EMAIL_ADDRESS;
UPDATE POS_CONTACT_EMAIL SET UPDATED = NOW();

ALTER TABLE POS_CONTACT_PHONE ADD COLUMN UPDATED DATETIME NOT NULL AFTER PHONE_TYPE;
UPDATE POS_CONTACT_PHONE SET UPDATED = NOW();

ALTER TABLE USER_GROUP ADD COLUMN UPDATED DATETIME NOT NULL AFTER NAME;
UPDATE USER_GROUP SET UPDATED = NOW();

ALTER TABLE DRIVER_LICENSE ADD COLUMN UPDATED DATETIME NOT NULL AFTER NUMBER;
UPDATE DRIVER_LICENSE SET UPDATED = NOW();

ALTER TABLE POS ADD COLUMN UPDATED DATETIME NOT NULL AFTER IS_PICKUP_AVAILABLE;
UPDATE POS SET UPDATED = NOW();

ALTER TABLE VEHICLE ADD COLUMN UPDATED DATETIME NOT NULL AFTER MODEL_NAME;
UPDATE VEHICLE SET UPDATED = NOW();

ALTER TABLE DRIVER ADD COLUMN UPDATED DATETIME NOT NULL AFTER ID_NUMBER;
UPDATE DRIVER SET UPDATED = NOW();

ALTER TABLE POLICY ADD COLUMN UPDATED DATETIME NOT NULL AFTER ID;
UPDATE POLICY SET UPDATED = NOW();

ALTER TABLE CASCO ADD COLUMN UPDATED DATETIME NOT NULL AFTER THIRD_PARTY_LIABILITY_COVERAGE;
UPDATE CASCO SET UPDATED = NOW();

/*
 * payment card bank
 */
ALTER TABLE INSURANCE_REQUEST ADD COLUMN PAYMENT_CARD_BANK VARCHAR(255) AFTER PAYMENT_CARD;

-- --->> MIGRATION FROM 2.4.3 TO 2.4.4

/*
 * VERSION TABLE
 */
DROP TABLE INSURANCE_VER_2_4;
CREATE TABLE INSURANCE_VER_2_5 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
