-- MIGRATION SCRIPT FROM 11 TO 12

-- FILL COMPLETED AND COMPLETED_BY FIELDS

UPDATE REQUEST r, INSURANCE_REQUEST ir
   SET r.COMPLETED = ir.PAYMENT_INSTANT,
       r.COMPLETED_BY_USER_ID = 0
 WHERE r.ID = ir.ID
   AND r.COMPLETED IS NULL
   AND ir.INSURANCE_REQUEST_STATUS = 'PREMIUM_PAID'
   AND ir.PAYMENT_INSTANT IS NOT NULL
   AND ir.AGREEMENT_NUMBER IS NOT NULL
   AND r.PROGRESS_STATUS = 'FINISHED'
;

UPDATE REQUEST r, INSURANCE_REQUEST ir
   SET r.COMPLETED = NOW(),
       r.COMPLETED_BY_USER_ID = 0
 WHERE r.ID = ir.ID
   AND r.COMPLETED IS NULL
   AND ir.INSURANCE_REQUEST_STATUS = 'REQUEST_CANCELED'
   AND r.PROGRESS_STATUS = 'FINISHED'
;

/*
 * VERSION TABLE
 */
DROP TABLE INSURANCE_VER_11;
CREATE TABLE INSURANCE_VER_12 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
