-- MIGRATION SCRIPT FROM 2.4.2 TO 2.4.3

ALTER TABLE INSURANCE_REQUEST
	ADD COLUMN PAYER_NAME VARCHAR(255) AFTER PAYMENT_METHOD_NAME;

/*
 * VERSION TABLE
 */
DROP TABLE INSURANCE_VER_2_4_2;
CREATE TABLE INSURANCE_VER_2_4_3 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
