-- MIGRATION SCRIPT FROM 2.4.4.1 TO 2.5

/*
 * policy and casco extending
 */
ALTER TABLE POLICY
	ADD COLUMN POLICY_NUMBER VARCHAR(255)  AFTER ID,
	ADD COLUMN DATE_OF_TERMINATION DATE  AFTER ID,
	ADD COLUMN DATE_OF_ISSUE DATE  AFTER ID,
	ADD COLUMN ACTUAL_CURRENCY VARCHAR(255) AFTER UPDATED,
	ADD COLUMN ACTUAL_AMOUNT DOUBLE AFTER UPDATED,
	ADD COLUMN INSURANT_PERSON_SURENAME VARCHAR(255) AFTER CALCULATED_CURRENCY, 
	ADD COLUMN INSURANT_PERSON_PATRONYMIC VARCHAR(255) AFTER CALCULATED_CURRENCY, 
	ADD COLUMN INSURANT_PERSON_NAME VARCHAR(255) AFTER CALCULATED_CURRENCY, 
	ADD COLUMN INSURANT_PERSON_GENDER VARCHAR(255) AFTER CALCULATED_CURRENCY, 
	ADD COLUMN INSURANT_PERSON_DOB DATE AFTER CALCULATED_CURRENCY, 
	ADD COLUMN INSURANT_COMPANY_NAME VARCHAR(255) AFTER CALCULATED_CURRENCY, 
	ADD COLUMN INSURANT_PHONE_NUMBER VARCHAR(255) AFTER CALCULATED_CURRENCY, 
	ADD COLUMN INSURANT_ID_NUMBER VARCHAR(255) AFTER CALCULATED_CURRENCY, 
	ADD COLUMN INSURANT_EMAIL VARCHAR(255) AFTER CALCULATED_CURRENCY; 

ALTER TABLE CASCO
	ADD COLUMN ACTUAL_CURRENCY VARCHAR(255) AFTER UPDATED,
	ADD COLUMN ACTUAL_AMOUNT DOUBLE AFTER UPDATED;

/*
 * VERSION TABLE
 */
DROP TABLE INSURANCE_VER_2_4_4_1;
CREATE TABLE INSURANCE_VER_2_5 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
