-- MIGRATION SCRIPT FROM 2.5.1 TO 2.5.2

/*
 * drop images
 */

ALTER TABLE IDENTITY_CARD 
	DROP FOREIGN KEY FK_IDENTITY_CARD_BACKSIDE_IMAGE_ID,
	DROP FOREIGN KEY FK_IDENTITY_CARD_FRONTSIDE_IMAGE_ID,
	DROP COLUMN BACKSIDE_IMAGE_ID,
	DROP COLUMN FRONTSIDE_IMAGE_ID; 

ALTER TABLE VEHICLE_CERTIFICATE 
	DROP FOREIGN KEY FK_VEHICLE_CERTIFICATE_BACKSIDE_IMAGE_ID,
	DROP FOREIGN KEY FK_VEHICLE_CERTIFICATE_FRONTSIDE_IMAGE_ID,
	DROP COLUMN BACKSIDE_IMAGE_ID,
	DROP COLUMN FRONTSIDE_IMAGE_ID; 

ALTER TABLE DRIVER_LICENSE
	DROP FOREIGN KEY FK_DRIVER_LICENSE_BACKSIDE_IMAGE_ID,
	DROP FOREIGN KEY FK_DRIVER_LICENSE_FRONTSIDE_IMAGE_ID,
	DROP COLUMN BACKSIDE_IMAGE_ID,
	DROP COLUMN FRONTSIDE_IMAGE_ID; 

ALTER TABLE CASCO_VEHICLE 
	DROP FOREIGN KEY FK_CASCO_VEHICLE_VIEW1_IMAGE_ID,
	DROP FOREIGN KEY FK_CASCO_VEHICLE_VIEW3_IMAGE_ID,
	DROP FOREIGN KEY FK_CASCO_VEHICLE_VIEW2_IMAGE_ID,
	DROP FOREIGN KEY FK_CASCO_VEHICLE_VIEW4_IMAGE_ID,
	DROP COLUMN VIEW1_IMAGE_ID,
	DROP COLUMN VIEW2_IMAGE_ID,
	DROP COLUMN VIEW3_IMAGE_ID,
	DROP COLUMN VIEW4_IMAGE_ID;

DROP TABLE IMAGE;

/*
 * VERSION TABLE
 */
DROP TABLE INSURANCE_VER_2_5_1;
CREATE TABLE INSURANCE_VER_2_5_2 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
