-- MIGRATION SCRIPT FROM 13 TO 14

-- REORDER FIELDS INSURANCE_REQUEST DUE TO PAYMENT_DATA REMOVAL

ALTER TABLE INSURANCE_REQUEST
	CHANGE COLUMN PAYMENT_AMOUNT DOUBLE AFTER AGREEMENT_NUMBER,
	CHANGE COLUMN PAYMENT_CARD VARCHAR(255) AFTER PAYMENT_CARD,
	CHANGE COLUMN PAYMENT_CARD_BANK VARCHAR(255) AFTER PAYMENT_CARD,
	CHANGE COLUMN PAYMENT_CURRENCY VARCHAR(255) AFTER PAYMENT_CARD_BANK,
	CHANGE COLUMN PAYMENT_INSTANT DATETIME AFTER PAYMENT_CURRENCY,
	CHANGE COLUMN INVOICE_AMOUNT DOUBLE AFTER INSURANCE_REQUEST_STATUS,
	CHANGE COLUMN INVOICE_CURRENCY VARCHAR(255) AFTER INVOICE_AMOUNT,
	CHANGE COLUMN INVOICE_LANGUAGE INTEGER AFTER INVOICE_CURRENCY,
	CHANGE COLUMN INVOICE_NUMBER VARCHAR(255) AFTER INVOICE_LANGUAGE,
	CHANGE COLUMN INVOICE_PAYEE_EMAIL VARCHAR(255) AFTER INVOICE_NUMBER,
	CHANGE COLUMN INVOICE_PAYEE_NAME VARCHAR(255) AFTER INVOICE_PAYEE_EMAIL,
	CHANGE COLUMN INVOICE_PAYEE_PHONE VARCHAR(255) AFTER INVOICE_PAYEE_NAME,
	CHANGE COLUMN INVOICE_PAYEE_TAXPAYER_NUMBER VARCHAR(255) AFTER INVOICE_PAYEE_PHONE,
	CHANGE COLUMN INVOICE_PRODUCT_NAME VARCHAR(255) AFTER INVOICE_PAYEE_TAXPAYER_NUMBER,
	CHANGE COLUMN INVOICE_QUANTITY INTEGER AFTER INVOICE_PRODUCT_NAME,
	CHANGE COLUMN PAYMENT_METHOD_NAME VARCHAR(255) AFTER INVOICE_QUANTITY,
	CHANGE COLUMN PAYER_NAME VARCHAR(255) AFTER PAYMENT_METHOD_NAME,
	CHANGE COLUMN PAYMENT_REFERENCE VARCHAR(255) AFTER PAYER_NAME;

/*
 * VERSION TABLE
 */
DROP TABLE INSURANCE_VER_13;
CREATE TABLE INSURANCE_VER_14 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
