-- MIGRATION SCRIPT FROM 2.4 TO 2.5

ALTER TABLE POLICY DROP COLUMN PAID_AMOUNT_TO_BE_REMOVED_IN_THE_NEXT_RELEASE; 
ALTER TABLE CASCO DROP COLUMN PAID_AMOUNT_TO_BE_REMOVED_IN_THE_NEXT_RELEASE;

/*
 * VERSION TABLE
 */
DROP TABLE INSURANCE_VER_2_4;
CREATE TABLE INSURANCE_VER_2_5 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
