-- MIGRATION SCRIPT FROM 14 TO 15

-- REORDER FIELDS INSURANCE_REQUEST AND ADD PAYMENT_CANCELED

ALTER TABLE INSURANCE_REQUEST
	MODIFY COLUMN AGREEMENT_NUMBER VARCHAR(255) AFTER ID,
	MODIFY COLUMN PAYMENT_CARD_BANK VARCHAR(255) AFTER AGREEMENT_NUMBER,
	MODIFY COLUMN INSURANCE_REQUEST_CANCELLATION_REASON VARCHAR(255) AFTER PAYMENT_CARD_BANK,
	MODIFY COLUMN INSURANCE_REQUEST_STATUS VARCHAR(255) AFTER INSURANCE_REQUEST_CANCELLATION_REASON,
	MODIFY COLUMN INVOICE_AMOUNT DOUBLE AFTER INSURANCE_REQUEST_STATUS,
	MODIFY COLUMN INVOICE_CURRENCY VARCHAR(255) AFTER INVOICE_AMOUNT,
	MODIFY COLUMN INVOICE_LANGUAGE INTEGER AFTER INVOICE_CURRENCY,
	MODIFY COLUMN INVOICE_NUMBER VARCHAR(255) AFTER INVOICE_LANGUAGE,
	MODIFY COLUMN INVOICE_PAYEE_EMAIL VARCHAR(255) AFTER INVOICE_NUMBER,
	MODIFY COLUMN INVOICE_PAYEE_NAME VARCHAR(255) AFTER INVOICE_PAYEE_EMAIL,
	MODIFY COLUMN INVOICE_PAYEE_PHONE VARCHAR(255) AFTER INVOICE_PAYEE_NAME,
	MODIFY COLUMN INVOICE_PAYEE_TAXPAYER_NUMBER VARCHAR(255) AFTER INVOICE_PAYEE_PHONE,
	MODIFY COLUMN INVOICE_PRODUCT_NAME VARCHAR(255) AFTER INVOICE_PAYEE_TAXPAYER_NUMBER,
	MODIFY COLUMN INVOICE_QUANTITY INTEGER AFTER INVOICE_PRODUCT_NAME,
	MODIFY COLUMN PAYER_NAME VARCHAR(255) AFTER INVOICE_QUANTITY,
	MODIFY COLUMN PAYMENT_AMOUNT DOUBLE AFTER PAYER_NAME,
	ADD COLUMN PAYMENT_CANCELED_INSTANT DATETIME AFTER PAYMENT_AMOUNT,
	MODIFY COLUMN PAYMENT_CARD VARCHAR(255) AFTER PAYMENT_CANCELED_INSTANT,
	MODIFY COLUMN PAYMENT_CURRENCY VARCHAR(255) AFTER PAYMENT_CARD,
	MODIFY COLUMN PAYMENT_INSTANT DATETIME AFTER PAYMENT_CURRENCY,
	MODIFY COLUMN PAYMENT_METHOD_NAME VARCHAR(255) AFTER PAYMENT_INSTANT,
	MODIFY COLUMN PAYMENT_REFERENCE VARCHAR(255) AFTER PAYMENT_METHOD_NAME,
	MODIFY COLUMN RTYPE VARCHAR(255) AFTER PAYMENT_REFERENCE;

/*
 * VERSION TABLE
 */
DROP TABLE INSURANCE_VER_14;
CREATE TABLE INSURANCE_VER_15 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
