-- MIGRATION SCRIPT FROM 12 TO 13

-- DROP COLUMN PAYMENT_STATUS
ALTER TABLE INSURANCE_REQUEST
    DROP COLUMN PAYMENT_STATUS;

/*
 * VERSION TABLE
 */
DROP TABLE INSURANCE_VER_12;
CREATE TABLE INSURANCE_VER_13 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
