-- MIGRATION SCRIPT FROM 2.4.3 TO 2.4.4

/*
 * opt lock
 */
ALTER TABLE IMAGE ADD COLUMN UPDATED DATETIME AFTER MIME_TYPE;
ALTER TABLE IDENTITY_CARD ADD COLUMN UPDATED DATETIME AFTER TYPE;
ALTER TABLE VEHICLE_CERTIFICATE ADD COLUMN UPDATED DATETIME AFTER VEHICLE_REGISTRATION_NUMBER;
ALTER TABLE USER ADD COLUMN UPDATED DATETIME AFTER NAME;
ALTER TABLE USER_LOGIN ADD COLUMN UPDATED DATETIME AFTER NAME;
ALTER TABLE POS_CONTACT_EMAIL ADD COLUMN UPDATED DATETIME AFTER EMAIL_ADDRESS;
ALTER TABLE POS_CONTACT_PHONE ADD COLUMN UPDATED DATETIME AFTER PHONE_TYPE;
ALTER TABLE USER_GROUP ADD COLUMN UPDATED DATETIME AFTER NAME;
ALTER TABLE DRIVER_LICENSE ADD COLUMN UPDATED DATETIME AFTER NUMBER;
ALTER TABLE INSURANCE_REQUEST ADD COLUMN UPDATED DATETIME AFTER yyy;
ALTER TABLE POS ADD COLUMN UPDATED DATETIME AFTER IS_PICKUP_AVAILABLE;
ALTER TABLE VEHICLE ADD COLUMN UPDATED DATETIME AFTER MODEL_NAME;
ALTER TABLE DRIVER ADD COLUMN UPDATED DATETIME AFTER ID_NUMBER;
ALTER TABLE POLICY ADD COLUMN UPDATED DATETIME AFTER ID;
ALTER TABLE CASCO ADD COLUMN UPDATED DATETIME AFTER THIRD_PARTY_LIABILITY_COVERAGE;

/*
 * VERSION TABLE
 */
DROP TABLE INSURANCE_VER_2_4_3;
CREATE TABLE INSURANCE_VER_2_4_4 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
