-- MIGRATION SCRIPT FROM 2.5.3 TO 10

-- ACCEPTED TO PICKED
ALTER TABLE REQUEST
	DROP FOREIGN KEY FK_REQUEST_ACCEPTED_BY_USER_ID,
	DROP KEY FK_REQUEST_ACCEPTED_BY_USER_ID,
	CHANGE COLUMN ACCEPTED PICKED DATETIME AFTER NOTE,
	CHANGE COLUMN ACCEPTED_BY_USER_ID PICKED_BY_USER_ID INTEGER AFTER CREATED_BY_USER_ID,
	ADD CONSTRAINT FK_REQUEST_PICKED_BY_USER_ID FOREIGN KEY (PICKED_BY_USER_ID) REFERENCES USER (ID);


-- INVOICE COLUMNS ADDITION
ALTER TABLE INSURANCE_REQUEST
	ADD COLUMN INVOICE_AMOUNT DOUBLE AFTER PAYMENT_INSTANT,
	ADD COLUMN INVOICE_CURRENCY VARCHAR(255) AFTER INVOICE_AMOUNT,
	ADD COLUMN INVOICE_LANGUAGE INTEGER AFTER INVOICE_CURRENCY, 
	CHANGE COLUMN PAYMENT_INVOICE_NUMBER INVOICE_NUMBER VARCHAR(255),
	ADD COLUMN INVOICE_PAYEE_EMAIL VARCHAR(255) AFTER INVOICE_NUMBER,
	ADD COLUMN INVOICE_PAYEE_NAME VARCHAR(255) AFTER INVOICE_PAYEE_EMAIL,
	ADD COLUMN INVOICE_PAYEE_PHONE VARCHAR(255) AFTER INVOICE_PAYEE_NAME,
	ADD COLUMN INVOICE_PAYEE_TAXPAYER_NUMBER VARCHAR(255) AFTER INVOICE_PAYEE_PHONE,
	ADD COLUMN INVOICE_PRODUCT_NAME VARCHAR(255) AFTER INVOICE_PAYEE_TAXPAYER_NUMBER,
	ADD COLUMN INVOICE_QUANTITY INTEGER AFTER INVOICE_PRODUCT_NAME;


/*
 * VERSION TABLE
 */
DROP TABLE INSURANCE_VER_2_5_3;
CREATE TABLE INSURANCE_VER_10 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
